language: java

#jdk:
#  - openjdk8
#
#install:
#    mvn test

env:
  - support_dio=true

after_success:
  # - mvn jacoco:report coveralls:report
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash)